### ISSUE TITLE
Single 96*96 image on titanx gpu takes longtime

### ISSUE THREAD

**Issue by tharuniitk** [corochann/SeRanet#5]
Hi

I have successfully installed and tried to run inference.py using basic_cnn_small model on a single GPU titanX, but it takes more than 3 hours and still going on, kindly help
(keras) tharun@nvidia-All-Series:~/keras/SeRanet$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import chainer
>>> chainer.cuda.available
True
>>> chainer.cuda.cudnn_enabled
True
>>> 
(keras) tharun@nvidia-All-Series:~/keras/SeRanet$ python src/inference.py /media/data_raid/tharun/noyawn/faces/0.png /media/data_raid/tharun/noyawn/01.png -g 2 -a basic_cnn_small
prepare model
setup model
loading data
upscaling to  /media/data_raid/tharun/noyawn/01.png

Regards
Tharun

**Comment by corochann** [comment]
I'm not sure, this is one possibilities: 

Is this png file 4 channels? (including alpha channel)
 → The model is trained to upscale 3 channel image (RGB).
     Can you try upscaling some jpeg file at first to see if it works or not?

**Comment by tharuniitk** [comment]
Yes I tried with the cubic.jpg in your repository too.. the program occupies 100% of the cpu and also a GPU memory usage of 300 MB, but it is running from past 12 minutes

(keras) tharun@nvidia-All-Series:~/keras/SeRanet$ python src/inference.py /media/data_raid/tharun/noyawn/faces/cubic.jpg /media/data_raid/tharun/noyawn/01.jpg -g 2 -a basic_cnn_small
prepare model
setup model
loading data
upscaling to  /media/data_raid/tharun/noyawn/01.jpg

$top 

 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
25755 tharun    20   0  0.119t 772796 203960 R  99.7  1.2  12:33.38 python   \

 How do i improve the speed, time???       
Regards
Tharun

**Comment by corochann** [comment]
Computation usually finishes in few seconds with GPU.
I guess it is some bug (stacking at some point), not just slow.

But I am not sure about the root cause...

If you can debug (print debug etc) to see where the code is stucking, it is helpful to answer. 
Another thing you can try is to further downgrade chainer version (I was using chainer 1.10 at the time of developing this).

**Comment by tharuniitk** [comment]
Downgrading chainer version to chainer 1.10 helped me. Thank you

**Comment by corochann** [comment]
I see.

Though this code is already a bit old,
if you are interested in learning about chainer, please look below to learn how to implement chainer.

This is compatible with version 2. 
http://corochann.com/deep-learning-tutorial-with-chainer

**Comment by tharuniitk** [comment]
Thank you @corochann.  At present I am working on a huge dataset consisting of 3 lakh images with three classes. I wish to train CNN on top of them. I am facing trouble in terms of computation time on a single GPU. Does chainer have support for multi-gpu?

**Comment by corochann** [comment]
Yes, you can use either MultiProcessParallelUpdater in chainer or chainermn (install additional package).
http://corochann.com/install-chainer-1401.html

Usage of MultiProcessParallelUpdater: https://github.com/chainer/chainer/blob/master/examples/imagenet/train_imagenet_data_parallel.py
Chainermn: https://github.com/chainer/chainermn


However to use these, you need to write the code compatible with latest version of chainer.
The code you need to change from v1 to v2 is not so many, please refer this blog.
http://corochann.com/chainer-v2-released-difference-from-v1-1318.html
