### ISSUE TITLE
batch process?

### ISSUE THREAD

**Issue by kenkroft** [corochann/SeRanet#6]
Hello ! everything is working, CUDA on GTX1080, I'd just really love to know how to process an entire folder of images ? 
Sorry this is maybe a noob question.
That would be amazing !

Many thanks

edit : nevermind, I found a way to do with shell. If anyone is interested, just create a .sh file in the folder , and put this inside : 

"
for file in images/*.png
do
    python src/inference.py -g 0 $file     
done
"

also create a folder called "images" with your pictures in it

**Comment by corochann** [comment]
thank you for sharing! and let me close the issue.
